---
name: Continuous Integration

on: [workflow_call, pull_request]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2


    - name: Python | Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Pre-Commit | Run
      uses: pre-commit/action@v3.0.0

    - name: Python | Install Requirements
      run: |
        pip install -e .[test]

    - name: Python | Pytest Unit
      run: |
        coverage run -m pytest tests/unit

    - name: Python | Coverage XML
      run: |
        coverage xml

    - if: github.event_name == 'pull_request'
      name: Python | Upload Coverage
      uses: orgoro/coverage@v3.1
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.8
        thresholdNew: 0.8

    - name: Docker | Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Kind | Install
      uses: helm/kind-action@v1.5.0
      with:
        install_only: true

    - name: Helm | Install
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Environment | Start
      run: |
        python -m scripts.start

    - name: Python | Pytest E2E
      run: |
        pytest tests/e2e
